Update schema import docs
Update import documentation to expected format as indicated from output error when not including database.

When using the existing `terraform import postgresql_schema.schema_foo my_schema` without specifying database the following error is produced.

```
Error: schema ID my_schema has not the expected format 'database.schema': [my_schema]
```

Docs updated to include missing database component of the ID.